
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 19 15:19:57 EDT 2011
//----------------------------------------------------

package cs4120.lg342.xi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 20;
  public static final int STRING_LITERAL = 3;
  public static final int OPEN_PAREN = 34;
  public static final int NOT_EQUAL = 30;
  public static final int INT = 8;
  public static final int MINUS = 18;
  public static final int SEMICOLON = 40;
  public static final int CHARACTER_LITERAL = 4;
  public static final int NOT = 22;
  public static final int AND = 27;
  public static final int LT = 23;
  public static final int CLOSE_PAREN = 35;
  public static final int USE = 15;
  public static final int OR = 28;
  public static final int COMMA = 39;
  public static final int BOOL = 9;
  public static final int GEQ = 26;
  public static final int PLUS = 17;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 29;
  public static final int TRUE = 6;
  public static final int error = 1;
  public static final int MODULO = 21;
  public static final int OPEN_BRACE = 36;
  public static final int CLOSE_BRACKET = 33;
  public static final int BREAK = 13;
  public static final int OPEN_BRACKET = 32;
  public static final int TIMES = 19;
  public static final int COLON = 38;
  public static final int ELSE = 11;
  public static final int WHILE = 12;
  public static final int LEQ = 24;
  public static final int UNDERSCORE = 41;
  public static final int CLOSE_BRACE = 37;
  public static final int GETS = 31;
  public static final int FALSE = 7;
  public static final int GT = 25;
  public static final int LENGTH = 16;
  public static final int INTEGER_LITERAL = 5;
  public static final int IDENTIFIER = 2;
}

