
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 11 17:20:51 EST 2011
//----------------------------------------------------

package cs4120.der34dlc287lg342.xi;

import edu.cornell.cs.cs4120.util.VisualizableTreeNode;
import edu.cornell.cs.cs4120.xi.AbstractSyntaxNode;
import edu.cornell.cs.cs4120.xi.CompilationException;
import edu.cornell.cs.cs4120.xi.lexer.Token;
import edu.cornell.cs.cs4120.xi.Position;
import cs4120.der34dlc287lg342.xi.ast.*;
import cs4120.der34dlc287lg342.xi.typechecker.XiPrimitiveType;
import java.util.ArrayList;
import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Dec 11 17:20:51 EST 2011
  */
public class ixiparser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ixiparser() {super();}

  /** Constructor which sets the default scanner. */
  public ixiparser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ixiparser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\040\000\002\002\004\000\002\003\003\000\002\006" +
    "\003\000\002\006\003\000\002\006\003\000\002\005\002" +
    "\000\002\005\003\000\002\004\006\000\002\010\002\000" +
    "\002\010\006\000\002\011\002\000\002\011\003\000\002" +
    "\011\005\000\002\007\002\000\002\007\005\000\002\007" +
    "\006\000\002\015\007\000\002\016\007\000\002\016\011" +
    "\000\002\013\003\000\002\013\003\000\002\013\004\000" +
    "\002\013\004\000\002\012\003\000\002\012\006\000\002" +
    "\017\006\000\002\014\005\000\002\014\005\000\002\002" +
    "\003\000\002\002\003\000\002\002\004\000\002\002\004" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\074\000\006\004\006\056\007\001\002\000\010\002" +
    "\075\004\006\056\007\001\002\000\010\002\uffe4\004\uffe4" +
    "\056\uffe4\001\002\000\030\002\000\004\000\044\000\046" +
    "\000\047\000\050\000\051\000\052\000\053\000\056\000" +
    "\057\000\001\002\000\004\004\006\001\002\000\004\046" +
    "\012\001\002\000\010\002\uffe5\004\uffe5\056\uffe5\001\002" +
    "\000\010\004\006\047\ufff7\053\ufff7\001\002\000\006\047" +
    "\031\053\030\001\002\000\006\047\ufff6\053\ufff6\001\002" +
    "\000\004\052\016\001\002\000\010\004\006\012\022\013" +
    "\020\001\002\000\010\044\ufff9\047\ufff9\053\ufff9\001\002" +
    "\000\020\002\ufffe\004\ufffe\044\ufffe\047\ufffe\051\ufffe\053" +
    "\ufffe\056\ufffe\001\002\000\020\002\ufffd\004\ufffd\044\ufffd" +
    "\047\ufffd\051\ufffd\053\ufffd\056\ufffd\001\002\000\020\002" +
    "\uffff\004\uffff\044\uffff\047\uffff\051\uffff\053\uffff\056\uffff" +
    "\001\002\000\010\044\024\047\ufffa\053\ufffa\001\002\000" +
    "\006\007\025\045\ufffc\001\002\000\004\045\ufffb\001\002" +
    "\000\004\045\027\001\002\000\020\002\ufff8\004\ufff8\044" +
    "\ufff8\047\ufff8\051\ufff8\053\ufff8\056\ufff8\001\002\000\004" +
    "\004\006\001\002\000\016\002\ufff4\004\ufff4\051\ufff4\052" +
    "\033\053\ufff4\056\ufff4\001\002\000\014\002\ufff1\004\ufff1" +
    "\051\ufff1\053\036\056\ufff1\001\002\000\010\004\006\012" +
    "\022\013\020\001\002\000\016\002\ufff9\004\ufff9\044\ufff9" +
    "\051\ufff9\053\ufff9\056\ufff9\001\002\000\016\002\ufff3\004" +
    "\ufff3\044\024\051\ufff3\053\ufff3\056\ufff3\001\002\000\010" +
    "\004\006\012\022\013\020\001\002\000\016\002\ufff9\004" +
    "\ufff9\044\ufff9\051\ufff9\053\ufff9\056\ufff9\001\002\000\016" +
    "\002\ufff2\004\ufff2\044\024\051\ufff2\053\ufff2\056\ufff2\001" +
    "\002\000\006\047\ufff5\053\ufff5\001\002\000\006\050\044" +
    "\057\043\001\002\000\004\004\006\001\002\000\004\004" +
    "\006\001\002\000\006\004\uffee\051\uffee\001\002\000\006" +
    "\004\uffea\051\uffea\001\002\000\006\052\064\053\063\001" +
    "\002\000\006\004\006\051\061\001\002\000\010\046\012" +
    "\052\054\053\053\001\002\000\006\004\uffed\051\uffed\001" +
    "\002\000\004\004\006\001\002\000\010\004\006\012\022" +
    "\013\020\001\002\000\010\004\ufff9\044\ufff9\051\ufff9\001" +
    "\002\000\010\004\uffe8\044\024\051\uffe8\001\002\000\006" +
    "\052\uffe7\053\uffe7\001\002\000\006\004\uffec\051\uffec\001" +
    "\002\000\010\002\ufff0\004\ufff0\056\ufff0\001\002\000\006" +
    "\004\uffeb\051\uffeb\001\002\000\004\004\006\001\002\000" +
    "\010\004\006\012\022\013\020\001\002\000\010\004\ufff9" +
    "\044\ufff9\051\ufff9\001\002\000\010\004\uffe9\044\024\051" +
    "\uffe9\001\002\000\006\052\uffe6\053\uffe6\001\002\000\004" +
    "\050\071\001\002\000\004\004\006\001\002\000\006\004" +
    "\006\051\073\001\002\000\010\002\uffef\004\uffef\056\uffef" +
    "\001\002\000\010\002\uffe2\004\uffe2\056\uffe2\001\002\000" +
    "\004\002\001\001\002\000\010\002\uffe3\004\uffe3\056\uffe3" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\074\000\012\002\003\003\007\015\010\016\004\001" +
    "\001\000\010\003\007\015\075\016\073\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\003\041\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\003\014\004\013" +
    "\011\012\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\003\020\006\016\001\001\000\004" +
    "\010\022\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\025\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\003\014\004\040\001\001\000\004\007\031\001\001" +
    "\000\002\001\001\000\006\003\020\006\033\001\001\000" +
    "\004\010\034\001\001\000\002\001\001\000\006\003\020" +
    "\006\036\001\001\000\004\010\037\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\003\067" +
    "\001\001\000\016\003\050\012\044\013\047\014\046\015" +
    "\051\017\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\003\050\012\057\014\046\015" +
    "\061\017\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\003\056\001\001\000\006\003\020\006\054\001" +
    "\001\000\004\010\055\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\003\066\001\001\000\006\003\020\006\064" +
    "\001\001\000\004\010\065\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\003\050\012\044" +
    "\013\071\014\046\015\051\017\045\001\001\000\014\003" +
    "\050\012\057\014\046\015\061\017\045\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ixiparser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ixiparser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ixiparser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public void syntax_error(Symbol cur_token){
		Token t = (Token)cur_token.value;
		if (t != null)
			throw new CompilationException("Syntax Error: Not expecting token "+t.type()+"("+t.value()+")", t.position());
		else
			throw new CompilationException("Syntax Error: Not expecting EOF", new XiPosition(0,0,0,0));
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ixiparser$actions {


	public Position span(Position left, Position right){
		return new XiPosition(left.unit(), left.columnStart(), right.columnEnd(), left.lineStart(), right.lineEnd());
	}

  private final ixiparser parser;

  /** Constructor */
  CUP$ixiparser$actions(ixiparser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ixiparser$do_action(
    int                        CUP$ixiparser$act_num,
    java_cup.runtime.lr_parser CUP$ixiparser$parser,
    java.util.Stack            CUP$ixiparser$stack,
    int                        CUP$ixiparser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ixiparser$result;

      /* select the action based on the action number */
      switch (CUP$ixiparser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // program ::= program class_decl 
            {
              AbstractSyntaxNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		AbstractSyntaxNode p = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode s = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			ProgramNode program = (ProgramNode)p;
		program.add(s);
		program.position = span(p.position(), s.position());
		RESULT = program; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // program ::= program func_decl 
            {
              AbstractSyntaxNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		AbstractSyntaxNode p = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode s = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			ProgramNode program = (ProgramNode)p;
		program.add(s);
		program.position = span(p.position(), s.position());
		RESULT = program; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // program ::= class_decl 
            {
              AbstractSyntaxNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode s = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			ProgramNode program = new ProgramNode(s.position());
		program.add(s);
		RESULT = program; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // program ::= func_decl 
            {
              AbstractSyntaxNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode s = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			ProgramNode program = new ProgramNode(s.position());
		program.add(s);
		RESULT = program; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // idclass_list ::= idclass_list COMMA id 
            {
              ArrayList<IdNode> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).right;
		ArrayList<IdNode> list = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode id = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		
		list.add((IdNode)id);
		RESULT = list;
	
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("idclass_list",10, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // idclass_list ::= id COMMA id 
            {
              ArrayList<IdNode> RESULT =null;
		int id1left = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).right;
		AbstractSyntaxNode id1 = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode id2 = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		
		ArrayList<IdNode> list = new ArrayList<IdNode>();
		list.add((IdNode)id1);
		list.add((IdNode)id2);
		RESULT = list;
	
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("idclass_list",10, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // varclass_decl ::= id COLON type bracket_list 
            {
              AbstractSyntaxNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).right;
		AbstractSyntaxNode id = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int arrleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int arrright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		ArrayList<VisualizableTreeNode> arr = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			// check that arr is empty
		ClassDeclNode decl = new ClassDeclNode((IdNode)id, t, arr, id.position());
		RESULT = decl;
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("varclass_decl",13, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // varclass_list ::= idclass_list COLON type bracket_list 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		int idlistleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).left;
		int idlistright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).right;
		ArrayList<IdNode> idlist = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int arrleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int arrright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		ArrayList<VisualizableTreeNode> arr = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			
		ArrayList<VisualizableTreeNode> list = new ArrayList<VisualizableTreeNode>();
		for (IdNode id : idlist){
			list.add(new ClassDeclNode(id, t, arr, id.position()));
		}
		RESULT = list; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("varclass_list",8, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // varclass_list ::= varclass_decl 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode s = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			ArrayList<VisualizableTreeNode> list = new ArrayList<VisualizableTreeNode>();
		list.add(s);
		RESULT = list; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("varclass_list",8, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // class_block ::= class_block func_decl 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		ArrayList<VisualizableTreeNode> list = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode s = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		
		list.add(s);
		RESULT = list;
	
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("class_block",9, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // class_block ::= class_block varclass_list 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		ArrayList<VisualizableTreeNode> list = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int declsleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int declsright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		ArrayList<VisualizableTreeNode> decls = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		
		list.addAll(decls);
		RESULT = list;
	
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("class_block",9, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // class_block ::= func_decl 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode s = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		
		ArrayList<VisualizableTreeNode> list = new ArrayList<VisualizableTreeNode>();
		list.add(s);
		RESULT = list;
	
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("class_block",9, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // class_block ::= varclass_list 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		ArrayList<VisualizableTreeNode> list = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		
		RESULT = list;
	
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("class_block",9, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // class_decl ::= CLASS id EXTENDS id OPEN_BRACE class_block CLOSE_BRACE 
            {
              AbstractSyntaxNode RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-6)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-6)).right;
		Token c = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-6)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-5)).right;
		AbstractSyntaxNode id = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-5)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).right;
		AbstractSyntaxNode ex = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		ArrayList<VisualizableTreeNode> b = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		
		ClassNode class_node = new ClassNode((IdNode)id, span(c.position(), e.position()));
		class_node.children.addAll(b);
		class_node.ex = (IdNode)ex;
		RESULT = class_node;
	
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("class_decl",12, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-6)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // class_decl ::= CLASS id OPEN_BRACE class_block CLOSE_BRACE 
            {
              AbstractSyntaxNode RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-4)).right;
		Token c = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).right;
		AbstractSyntaxNode id = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		ArrayList<VisualizableTreeNode> b = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		Token e = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		
		ClassNode class_node = new ClassNode((IdNode)id, span(c.position(), e.position()));
		class_node.children.addAll(b);
		RESULT = class_node;
	
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("class_decl",12, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-4)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // func_decl ::= id OPEN_PAREN func_list CLOSE_PAREN types 
            {
              AbstractSyntaxNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-4)).right;
		AbstractSyntaxNode id = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-4)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).right;
		ArrayList<VisualizableTreeNode> list = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).value;
		int typesleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int typesright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		ArrayList<XiPrimitiveType> types = (ArrayList<XiPrimitiveType>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			FuncDeclNode func_decl = new FuncDeclNode((IdNode)id, list, types, null, id.position());
		RESULT = func_decl; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("func_decl",11, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-4)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // types ::= types COMMA type bracket_list 
            {
              ArrayList<XiPrimitiveType> RESULT =null;
		int arrleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).left;
		int arrright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).right;
		ArrayList<XiPrimitiveType> arr = (ArrayList<XiPrimitiveType>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int dimleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int dimright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		ArrayList<VisualizableTreeNode> dim = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			RESULT = arr;
		arr.add(new XiPrimitiveType(type, dim)); 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("types",5, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // types ::= COLON type bracket_list 
            {
              ArrayList<XiPrimitiveType> RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int dimleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int dimright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		ArrayList<VisualizableTreeNode> dim = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		 RESULT = new ArrayList<XiPrimitiveType>(); RESULT.add(new XiPrimitiveType(type, dim)); 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("types",5, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // types ::= 
            {
              ArrayList<XiPrimitiveType> RESULT =null;
		 RESULT = new ArrayList<XiPrimitiveType>(); 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("types",5, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // func_list ::= func_list COMMA var_decl 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).right;
		ArrayList<VisualizableTreeNode> list = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode s = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			list.add(s);
		RESULT = list; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("func_list",7, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-2)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // func_list ::= var_decl 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode s = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			ArrayList<VisualizableTreeNode> list = new ArrayList<VisualizableTreeNode>();
		list.add(s);
		RESULT = list; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("func_list",7, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // func_list ::= 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
			ArrayList<VisualizableTreeNode> list = new ArrayList<VisualizableTreeNode>();
		RESULT = list; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("func_list",7, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // bracket_list ::= bracket_list OPEN_BRACKET dimension CLOSE_BRACKET 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		int arrleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).left;
		int arrright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).right;
		ArrayList<VisualizableTreeNode> arr = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		VisualizableTreeNode t = (VisualizableTreeNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		 	if (arr == null) arr = new ArrayList<VisualizableTreeNode>();
		arr.add(t);
		RESULT = arr; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("bracket_list",6, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // bracket_list ::= 
            {
              ArrayList<VisualizableTreeNode> RESULT =null;
		 RESULT = new ArrayList<VisualizableTreeNode>(); 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("bracket_list",6, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // var_decl ::= id COLON type bracket_list 
            {
              AbstractSyntaxNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).right;
		AbstractSyntaxNode id = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		int arrleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int arrright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		ArrayList<VisualizableTreeNode> arr = (ArrayList<VisualizableTreeNode>)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			// check that arr is empty
		DeclNode decl = new DeclNode((IdNode)id, t, arr, id.position());
		RESULT = decl;
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("var_decl",2, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-3)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // dimension ::= INTEGER_LITERAL 
            {
              VisualizableTreeNode RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
			String s = t.value();
		RESULT = new IntegerLiteralNode(Long.parseLong(s), t.position()); 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("dimension",3, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // dimension ::= 
            {
              VisualizableTreeNode RESULT =null;

              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("dimension",3, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // type ::= id 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		AbstractSyntaxNode id = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		 RESULT = ((IdNode)id).id; 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // type ::= BOOL 
            {
              String RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		Token o = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		 RESULT = o.value(); 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // type ::= INT 
            {
              String RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		Token o = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		 RESULT = o.value(); 
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // id ::= IDENTIFIER 
            {
              AbstractSyntaxNode RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()).right;
		Token o = (Token)((java_cup.runtime.Symbol) CUP$ixiparser$stack.peek()).value;
		  Token id = (Token)o;
		RESULT = new IdNode(id.value(), id.position());
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("id",1, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          return CUP$ixiparser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).right;
		AbstractSyntaxNode start_val = (AbstractSyntaxNode)((java_cup.runtime.Symbol) CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)).value;
		RESULT = start_val;
              CUP$ixiparser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ixiparser$stack.elementAt(CUP$ixiparser$top-1)), ((java_cup.runtime.Symbol)CUP$ixiparser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ixiparser$parser.done_parsing();
          return CUP$ixiparser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

