
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 15 08:30:25 EST 2011
//----------------------------------------------------

package cs4120.der34dlc287lg342.xi;

/** CUP generated class containing symbol constants. */
public class ixisym {
  /* terminals */
  public static final int DIVIDE = 23;
  public static final int OPEN_PAREN = 37;
  public static final int STRING_LITERAL = 3;
  public static final int PERIOD = 49;
  public static final int UMINUS = 11;
  public static final int NOT_EQUAL = 33;
  public static final int UNOT = 12;
  public static final int INT = 8;
  public static final int MINUS = 21;
  public static final int SEMICOLON = 43;
  public static final int CHARACTER_LITERAL = 4;
  public static final int NOT = 25;
  public static final int AND = 30;
  public static final int LT = 26;
  public static final int CLOSE_PAREN = 38;
  public static final int USE = 18;
  public static final int OR = 31;
  public static final int COMMA = 42;
  public static final int BOOL = 9;
  public static final int CLASS = 45;
  public static final int GEQ = 29;
  public static final int PLUS = 20;
  public static final int IF = 13;
  public static final int THIS = 48;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int EQUAL = 32;
  public static final int TRUE = 6;
  public static final int NEW = 47;
  public static final int error = 1;
  public static final int MODULO = 24;
  public static final int NULL = 50;
  public static final int OPEN_BRACE = 39;
  public static final int CLOSE_BRACKET = 36;
  public static final int OPEN_BRACKET = 35;
  public static final int BREAK = 16;
  public static final int TIMES = 22;
  public static final int COLON = 41;
  public static final int ELSE = 14;
  public static final int FINAL = 10;
  public static final int WHILE = 15;
  public static final int EXTENDS = 46;
  public static final int LEQ = 27;
  public static final int UNDERSCORE = 44;
  public static final int CLOSE_BRACE = 40;
  public static final int GETS = 34;
  public static final int FALSE = 7;
  public static final int GT = 28;
  public static final int LENGTH = 19;
  public static final int INTEGER_LITERAL = 5;
  public static final int IDENTIFIER = 2;

  /* non terminals */
  static final int class_decl = 12;
  static final int id = 1;
  static final int bracket_list = 6;
  static final int varclass_list = 8;
  static final int dimension = 3;
  static final int func_list = 7;
  static final int program = 0;
  static final int varclass_decl = 13;
  static final int func_decl = 11;
  static final int class_block = 9;
  static final int types = 5;
  static final int type = 4;
  static final int idclass_list = 10;
  static final int var_decl = 2;
}

