
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 15 09:33:46 EST 2011
//----------------------------------------------------

package cs4120.der34dlc287lg342.xi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 24;
  public static final int OPEN_PAREN = 38;
  public static final int STRING_LITERAL = 3;
  public static final int PERIOD = 50;
  public static final int UMINUS = 12;
  public static final int NOT_EQUAL = 34;
  public static final int CONTINUE = 11;
  public static final int UNOT = 13;
  public static final int INT = 8;
  public static final int MINUS = 22;
  public static final int SEMICOLON = 44;
  public static final int CHARACTER_LITERAL = 4;
  public static final int NOT = 26;
  public static final int AND = 31;
  public static final int LT = 27;
  public static final int CLOSE_PAREN = 39;
  public static final int USE = 19;
  public static final int OR = 32;
  public static final int COMMA = 43;
  public static final int BOOL = 9;
  public static final int CLASS = 46;
  public static final int GEQ = 30;
  public static final int PLUS = 21;
  public static final int IF = 14;
  public static final int THIS = 49;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int EQUAL = 33;
  public static final int TRUE = 6;
  public static final int NEW = 48;
  public static final int error = 1;
  public static final int MODULO = 25;
  public static final int NULL = 51;
  public static final int OPEN_BRACE = 40;
  public static final int CLOSE_BRACKET = 37;
  public static final int OPEN_BRACKET = 36;
  public static final int BREAK = 17;
  public static final int TIMES = 23;
  public static final int COLON = 42;
  public static final int ELSE = 15;
  public static final int FINAL = 10;
  public static final int WHILE = 16;
  public static final int EXTENDS = 47;
  public static final int LEQ = 28;
  public static final int UNDERSCORE = 45;
  public static final int CLOSE_BRACE = 41;
  public static final int GETS = 35;
  public static final int FALSE = 7;
  public static final int GT = 29;
  public static final int LENGTH = 20;
  public static final int INTEGER_LITERAL = 5;
  public static final int IDENTIFIER = 2;
}

