
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 15 09:44:12 EST 2011
//----------------------------------------------------

package cs4120.der34dlc287lg342.xi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 24;
  public static final int OPEN_PAREN = 38;
  public static final int STRING_LITERAL = 3;
  public static final int PERIOD = 50;
  public static final int UMINUS = 12;
  public static final int NOT_EQUAL = 34;
  public static final int CONTINUE = 11;
  public static final int UNOT = 13;
  public static final int INT = 8;
  public static final int MINUS = 22;
  public static final int SEMICOLON = 44;
  public static final int CHARACTER_LITERAL = 4;
  public static final int NOT = 26;
  public static final int AND = 31;
  public static final int LT = 27;
  public static final int CLOSE_PAREN = 39;
  public static final int USE = 19;
  public static final int OR = 32;
  public static final int COMMA = 43;
  public static final int BOOL = 9;
  public static final int CLASS = 46;
  public static final int GEQ = 30;
  public static final int PLUS = 21;
  public static final int IF = 14;
  public static final int THIS = 49;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int EQUAL = 33;
  public static final int TRUE = 6;
  public static final int NEW = 48;
  public static final int error = 1;
  public static final int MODULO = 25;
  public static final int NULL = 51;
  public static final int OPEN_BRACE = 40;
  public static final int CLOSE_BRACKET = 37;
  public static final int OPEN_BRACKET = 36;
  public static final int BREAK = 17;
  public static final int TIMES = 23;
  public static final int COLON = 42;
  public static final int ELSE = 15;
  public static final int FINAL = 10;
  public static final int WHILE = 16;
  public static final int EXTENDS = 47;
  public static final int LEQ = 28;
  public static final int UNDERSCORE = 45;
  public static final int CLOSE_BRACE = 41;
  public static final int GETS = 35;
  public static final int FALSE = 7;
  public static final int GT = 29;
  public static final int LENGTH = 20;
  public static final int INTEGER_LITERAL = 5;
  public static final int IDENTIFIER = 2;

  /* non terminals */
  static final int program = 0;
  static final int uop = 3;
  static final int arr_create = 7;
  static final int gblvar_list = 37;
  static final int allowed_element_assign = 11;
  static final int varclass_inst = 48;
  static final int arr_index = 6;
  static final int id_brackets = 10;
  static final int var_decl = 23;
  static final int block = 19;
  static final int usable_id = 12;
  static final int gblvar_inst = 50;
  static final int stmt_w_semi = 14;
  static final int attr = 43;
  static final int arr_elements = 8;
  static final int return_stmt = 17;
  static final int func_list = 33;
  static final int idclass_list = 38;
  static final int varclass_decl = 47;
  static final int stmt_or_block = 22;
  static final int block_stmt = 21;
  static final int final_type = 41;
  static final int class_block = 36;
  static final int use_stmt = 45;
  static final int func_callargs = 34;
  static final int gblvar_decl = 49;
  static final int while_stmt = 16;
  static final int stmt_list = 20;
  static final int var_set = 26;
  static final int id = 9;
  static final int class_decl = 46;
  static final int final_var_init = 28;
  static final int final_var_decl = 27;
  static final int var_list = 32;
  static final int dimension = 29;
  static final int types = 30;
  static final int expr = 2;
  static final int bracket_list = 31;
  static final int return_list = 18;
  static final int func_decl = 44;
  static final int if_stmt = 15;
  static final int var_item = 25;
  static final int gblid_list = 39;
  static final int var_inst = 24;
  static final int bool_literal = 42;
  static final int expr_subset = 5;
  static final int stmt = 13;
  static final int use_list = 1;
  static final int type = 40;
  static final int varclass_list = 35;
  static final int func_call = 4;
}

