/* The following code was generated by JFlex 1.4.3 on 10/2/11 5:44 PM */

package cs4120.der34dlc287lg342.xi;

import java.util.NoSuchElementException;
import edu.cornell.cs.cs4120.xi.lexer.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/2/11 5:44 PM from the specification file
 * <tt>/Users/danchen/Documents/eclipse/workspace/Xi/bin/cs4120/der34dlc287lg342/xi/grammar.jflex</tt>
 */
public class XiLexer implements Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\36\1\31"+
    "\2\0\1\35\1\42\1\6\1\46\1\47\1\34\1\32\1\53\1\33"+
    "\1\0\1\4\1\7\11\10\1\52\1\54\1\37\1\40\1\41\2\0"+
    "\32\5\1\44\1\56\1\45\1\0\1\55\1\0\1\22\1\20\2\5"+
    "\1\13\1\12\1\27\1\17\1\11\1\5\1\23\1\14\1\5\1\26"+
    "\1\30\2\5\1\21\1\15\1\24\1\25\1\5\1\16\3\5\1\50"+
    "\1\43\1\51\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\1\2\5\11\4"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\2\2\0\1\36\12\4\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\2\47\3\0\1\50\10\4"+
    "\1\51\1\52\1\53\1\54\1\55\1\4\1\56\3\4"+
    "\1\57\1\4\1\60\1\61\1\4\1\62\1\63\1\4"+
    "\1\64\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\136\0\274\0\353\0\u011a"+
    "\0\136\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263"+
    "\0\u0292\0\u02c1\0\u02f0\0\136\0\136\0\136\0\136\0\136"+
    "\0\u031f\0\u034e\0\u037d\0\u03ac\0\136\0\136\0\136\0\136"+
    "\0\136\0\136\0\136\0\136\0\136\0\136\0\136\0\136"+
    "\0\u03db\0\136\0\u040a\0\u0439\0\u0468\0\u0497\0\353\0\u04c6"+
    "\0\u04f5\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e"+
    "\0\u066d\0\136\0\136\0\136\0\136\0\136\0\136\0\136"+
    "\0\136\0\136\0\u069c\0\u06cb\0\u06fa\0\u0729\0\353\0\u0758"+
    "\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\353"+
    "\0\136\0\136\0\136\0\136\0\u08d0\0\353\0\u08ff\0\u092e"+
    "\0\u095d\0\353\0\u098c\0\353\0\353\0\u09bb\0\353\0\353"+
    "\0\u09ea\0\353\0\353";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\7\1\17\1\7\1\20"+
    "\1\21\2\7\1\22\1\23\3\7\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\3\1\51\2\3\26\51\1\52\24\51"+
    "\1\53\61\0\1\5\60\0\1\54\57\0\24\7\24\0"+
    "\1\7\1\0\6\55\1\0\47\55\1\56\7\0\2\12"+
    "\53\0\5\7\1\57\13\7\1\60\2\7\24\0\1\7"+
    "\6\0\15\7\1\61\6\7\24\0\1\7\6\0\7\7"+
    "\1\62\14\7\24\0\1\7\6\0\6\7\1\63\15\7"+
    "\24\0\1\7\6\0\12\7\1\64\11\7\24\0\1\7"+
    "\6\0\14\7\1\65\6\7\1\66\24\0\1\7\6\0"+
    "\6\7\1\67\15\7\24\0\1\7\6\0\14\7\1\70"+
    "\7\7\24\0\1\7\6\0\10\7\1\71\13\7\24\0"+
    "\1\7\41\0\1\72\56\0\1\73\56\0\1\74\56\0"+
    "\1\75\16\0\1\51\2\0\26\51\1\0\24\51\22\0"+
    "\1\76\2\0\1\77\1\0\1\100\2\0\1\101\25\0"+
    "\1\54\2\0\54\54\6\0\1\102\56\0\1\103\12\0"+
    "\1\104\2\0\1\105\1\0\1\106\35\0\17\7\1\107"+
    "\4\7\24\0\1\7\6\0\7\7\1\110\14\7\24\0"+
    "\1\7\6\0\10\7\1\111\13\7\24\0\1\7\6\0"+
    "\21\7\1\112\2\7\24\0\1\7\6\0\4\7\1\113"+
    "\17\7\24\0\1\7\6\0\6\7\1\114\15\7\24\0"+
    "\1\7\6\0\23\7\1\115\24\0\1\7\6\0\17\7"+
    "\1\116\4\7\24\0\1\7\6\0\20\7\1\117\3\7"+
    "\24\0\1\7\6\0\6\7\1\120\15\7\24\0\1\7"+
    "\7\0\1\121\56\0\1\122\56\0\1\123\56\0\1\124"+
    "\55\0\10\7\1\125\13\7\24\0\1\7\6\0\6\7"+
    "\1\126\15\7\24\0\1\7\6\0\22\7\1\127\1\7"+
    "\24\0\1\7\6\0\7\7\1\130\14\7\24\0\1\7"+
    "\6\0\15\7\1\131\6\7\24\0\1\7\6\0\7\7"+
    "\1\132\14\7\24\0\1\7\6\0\20\7\1\133\3\7"+
    "\24\0\1\7\6\0\6\7\1\134\15\7\24\0\1\7"+
    "\6\0\6\7\1\135\15\7\24\0\1\7\6\0\17\7"+
    "\1\136\4\7\24\0\1\7\6\0\6\7\1\137\15\7"+
    "\24\0\1\7\6\0\16\7\1\140\5\7\24\0\1\7"+
    "\6\0\14\7\1\141\7\7\24\0\1\7\6\0\12\7"+
    "\1\142\11\7\24\0\1\7\6\0\21\7\1\143\2\7"+
    "\24\0\1\7\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2585];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\3\1\1\11\12\1\5\11"+
    "\4\1\14\11\1\1\1\11\2\1\2\0\13\1\11\11"+
    "\1\1\3\0\12\1\4\11\17\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();
	private boolean isEOF = false;
	public String unit = "";
	protected Token nextToken = null;
	protected Token cached_token = null;
	protected int yycolumn_cache = 0;
	
	@Override
	public Token next(){
		Token next;
		try{
			if (nextToken == null){
				next = lex();
				if (next == null){
					throw new NoSuchElementException();
				}
			}else{
				next = nextToken;
				nextToken = null;
			}
		} catch (java.io.IOException e){
			next = null;
			e.printStackTrace();
		}
		nextToken = null;
		cached_token = next;
		return next;
	}
	
	@Override
	public void remove() {
		throw new UnsupportedOperationException();
	}
	
	@Override
	public boolean hasNext() {
		try{
			if (nextToken == null)
				nextToken = lex();
		} catch (java.io.IOException e){
			return false;
		}
		return !isEOF;
	}
	
	private Token token(TokenType type, String value){
		int col = yycolumn, line = yyline;
		int newlines = value.split("\n").length-1;
		String lastline = value.split("\n")[newlines];
		if (newlines > 0)
			col = lastline.length();
		else
			col += lastline.length();
		
		return new XiToken(value, type, unit, yycolumn+1, yycolumn+yylength(), yyline+1, line+newlines+1);
	}
	
	private Token token(TokenType type){
		return token(type, yytext());
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public XiLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public XiLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    	isEOF = true;

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token lex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { /* ignore */
          }
        case 54: break;
        case 49: 
          { return token(TokenType.FALSE);
          }
        case 55: break;
        case 19: 
          { return token(TokenType.OPEN_PAREN);
          }
        case 56: break;
        case 42: 
          { return token(TokenType.CHARACTER_LITERAL, "\'");
          }
        case 57: break;
        case 5: 
          { return token(TokenType.INTEGER_LITERAL);
          }
        case 58: break;
        case 41: 
          { return token(TokenType.USE);
          }
        case 59: break;
        case 13: 
          { return token(TokenType.GETS);
          }
        case 60: break;
        case 6: 
          { string.setLength(0); yybegin(STRING);
          }
        case 61: break;
        case 52: 
          { return token(TokenType.LENGTH);
          }
        case 62: break;
        case 22: 
          { return token(TokenType.CLOSE_BRACE);
          }
        case 63: break;
        case 10: 
          { return token(TokenType.MODULO);
          }
        case 64: break;
        case 31: 
          { return token(TokenType.NOT_EQUAL);
          }
        case 65: break;
        case 45: 
          { return token(TokenType.CHARACTER_LITERAL, "\n");
          }
        case 66: break;
        case 39: 
          { String s = yytext().substring(1,yytext().length()-1); 
                                   return token(TokenType.CHARACTER_LITERAL, s);
          }
        case 67: break;
        case 7: 
          { return token(TokenType.PLUS);
          }
        case 68: break;
        case 18: 
          { return token(TokenType.CLOSE_BRACKET);
          }
        case 69: break;
        case 28: 
          { yybegin(YYINITIAL); 
                                   yycolumn -= yycolumn_cache + 1; // -1 for the starting "
                                   yycolumn_cache = 0;
                                   return token(TokenType.STRING_LITERAL, 
                                   string.toString());
          }
        case 70: break;
        case 4: 
          { return token(TokenType.IDENTIFIER);
          }
        case 71: break;
        case 48: 
          { return token(TokenType.TRUE);
          }
        case 72: break;
        case 1: 
          { throw new Error("Illegal character <"+
                                                    yytext()+">");
          }
        case 73: break;
        case 14: 
          { return token(TokenType.GT);
          }
        case 74: break;
        case 53: 
          { return token(TokenType.RETURN);
          }
        case 75: break;
        case 46: 
          { return token(TokenType.ELSE);
          }
        case 76: break;
        case 12: 
          { return token(TokenType.LT);
          }
        case 77: break;
        case 32: 
          { return token(TokenType.LEQ);
          }
        case 78: break;
        case 29: 
          { string.append("\\\\"); yycolumn_cache += 2;
          }
        case 79: break;
        case 27: 
          { string.append( yytext() ); yycolumn_cache += yytext().length();
          }
        case 80: break;
        case 9: 
          { return token(TokenType.TIMES);
          }
        case 81: break;
        case 25: 
          { return token(TokenType.SEMICOLON);
          }
        case 82: break;
        case 23: 
          { return token(TokenType.COLON);
          }
        case 83: break;
        case 36: 
          { string.append("\\t"); yycolumn_cache += 2;
          }
        case 84: break;
        case 17: 
          { return token(TokenType.OPEN_BRACKET);
          }
        case 85: break;
        case 20: 
          { return token(TokenType.CLOSE_PAREN);
          }
        case 86: break;
        case 47: 
          { return token(TokenType.BOOL);
          }
        case 87: break;
        case 26: 
          { return token(TokenType.UNDERSCORE);
          }
        case 88: break;
        case 35: 
          { string.append("\\r"); yycolumn_cache += 2;
          }
        case 89: break;
        case 33: 
          { return token(TokenType.EQUAL);
          }
        case 90: break;
        case 51: 
          { return token(TokenType.BREAK);
          }
        case 91: break;
        case 50: 
          { return token(TokenType.WHILE);
          }
        case 92: break;
        case 40: 
          { return token(TokenType.INT);
          }
        case 93: break;
        case 21: 
          { return token(TokenType.OPEN_BRACE);
          }
        case 94: break;
        case 11: 
          { return token(TokenType.NOT);
          }
        case 95: break;
        case 15: 
          { return token(TokenType.AND);
          }
        case 96: break;
        case 44: 
          { return token(TokenType.CHARACTER_LITERAL, "\t");
          }
        case 97: break;
        case 37: 
          { string.append("\\n"); yycolumn_cache += 2;
          }
        case 98: break;
        case 30: 
          { return token(TokenType.IF);
          }
        case 99: break;
        case 8: 
          { return token(TokenType.MINUS);
          }
        case 100: break;
        case 34: 
          { return token(TokenType.GEQ);
          }
        case 101: break;
        case 43: 
          { return token(TokenType.CHARACTER_LITERAL, "\r");
          }
        case 102: break;
        case 16: 
          { return token(TokenType.OR);
          }
        case 103: break;
        case 3: 
          { return token(TokenType.DIVIDE);
          }
        case 104: break;
        case 38: 
          { string.append("\\\""); yycolumn_cache += 2;
          }
        case 105: break;
        case 24: 
          { return token(TokenType.COMMA);
          }
        case 106: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
